### ISSUE TITLE
Cant Play Video

### ISSUE THREAD

**Issue by ksharindam** [peterderivaz/pyopenmax#2]
When I am trying to play any video, such as /opt/vc/src/hello_pi/hello_video/test.h264 it show this error.
And the video is not played.
```python
Traceback (most recent call last):
  File "./pyopenmax.py", line 1004, in <module>
    play("/opt/vc/src/hello_pi/hello_video/test.h264") 
  File "./pyopenmax.py", line 983, in play
    vp = VideoPlayer(videofile)
  File "./pyopenmax.py", line 863, in __init__
    read_media.change_state(OMX_StateIdle)
  File "./pyopenmax.py", line 592, in change_state
    raise ValueError("State not reached")
ValueError: State not reached
```

**Comment by nulijiabei** [comment]
Error code 0x80001000L
Traceback (most recent call last):
  File "pyopenmax.py", line 1001, in <module>
    play("/opt/vc/src/hello_pi/hello_video/test.h264") 
  File "pyopenmax.py", line 982, in play
    vp = VideoPlayer(videofile)
  File "pyopenmax.py", line 854, in __init__
    read_media = ReadMediaComponent()
  File "pyopenmax.py", line 646, in __init__
    super(ReadMediaComponent,self).__init__("read_media")
  File "pyopenmax.py", line 471, in __init__
    check(e)
  File "pyopenmax.py", line 433, in check
    raise ValueError
ValueError
